// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	mm_domain "github.com/zlietapki/gena/internal/domain"
)

// IUsecaseMock implements mm_domain.IUsecase
type IUsecaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetCounter          func() (c1 mm_domain.Counter, err error)
	funcGetCounterOrigin    string
	inspectFuncGetCounter   func()
	afterGetCounterCounter  uint64
	beforeGetCounterCounter uint64
	GetCounterMock          mIUsecaseMockGetCounter
}

// NewIUsecaseMock returns a mock for mm_domain.IUsecase
func NewIUsecaseMock(t minimock.Tester) *IUsecaseMock {
	m := &IUsecaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetCounterMock = mIUsecaseMockGetCounter{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIUsecaseMockGetCounter struct {
	optional           bool
	mock               *IUsecaseMock
	defaultExpectation *IUsecaseMockGetCounterExpectation
	expectations       []*IUsecaseMockGetCounterExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IUsecaseMockGetCounterExpectation specifies expectation struct of the IUsecase.GetCounter
type IUsecaseMockGetCounterExpectation struct {
	mock *IUsecaseMock

	results      *IUsecaseMockGetCounterResults
	returnOrigin string
	Counter      uint64
}

// IUsecaseMockGetCounterResults contains results of the IUsecase.GetCounter
type IUsecaseMockGetCounterResults struct {
	c1  mm_domain.Counter
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetCounter *mIUsecaseMockGetCounter) Optional() *mIUsecaseMockGetCounter {
	mmGetCounter.optional = true
	return mmGetCounter
}

// Expect sets up expected params for IUsecase.GetCounter
func (mmGetCounter *mIUsecaseMockGetCounter) Expect() *mIUsecaseMockGetCounter {
	if mmGetCounter.mock.funcGetCounter != nil {
		mmGetCounter.mock.t.Fatalf("IUsecaseMock.GetCounter mock is already set by Set")
	}

	if mmGetCounter.defaultExpectation == nil {
		mmGetCounter.defaultExpectation = &IUsecaseMockGetCounterExpectation{}
	}

	return mmGetCounter
}

// Inspect accepts an inspector function that has same arguments as the IUsecase.GetCounter
func (mmGetCounter *mIUsecaseMockGetCounter) Inspect(f func()) *mIUsecaseMockGetCounter {
	if mmGetCounter.mock.inspectFuncGetCounter != nil {
		mmGetCounter.mock.t.Fatalf("Inspect function is already set for IUsecaseMock.GetCounter")
	}

	mmGetCounter.mock.inspectFuncGetCounter = f

	return mmGetCounter
}

// Return sets up results that will be returned by IUsecase.GetCounter
func (mmGetCounter *mIUsecaseMockGetCounter) Return(c1 mm_domain.Counter, err error) *IUsecaseMock {
	if mmGetCounter.mock.funcGetCounter != nil {
		mmGetCounter.mock.t.Fatalf("IUsecaseMock.GetCounter mock is already set by Set")
	}

	if mmGetCounter.defaultExpectation == nil {
		mmGetCounter.defaultExpectation = &IUsecaseMockGetCounterExpectation{mock: mmGetCounter.mock}
	}
	mmGetCounter.defaultExpectation.results = &IUsecaseMockGetCounterResults{c1, err}
	mmGetCounter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetCounter.mock
}

// Set uses given function f to mock the IUsecase.GetCounter method
func (mmGetCounter *mIUsecaseMockGetCounter) Set(f func() (c1 mm_domain.Counter, err error)) *IUsecaseMock {
	if mmGetCounter.defaultExpectation != nil {
		mmGetCounter.mock.t.Fatalf("Default expectation is already set for the IUsecase.GetCounter method")
	}

	if len(mmGetCounter.expectations) > 0 {
		mmGetCounter.mock.t.Fatalf("Some expectations are already set for the IUsecase.GetCounter method")
	}

	mmGetCounter.mock.funcGetCounter = f
	mmGetCounter.mock.funcGetCounterOrigin = minimock.CallerInfo(1)
	return mmGetCounter.mock
}

// Times sets number of times IUsecase.GetCounter should be invoked
func (mmGetCounter *mIUsecaseMockGetCounter) Times(n uint64) *mIUsecaseMockGetCounter {
	if n == 0 {
		mmGetCounter.mock.t.Fatalf("Times of IUsecaseMock.GetCounter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetCounter.expectedInvocations, n)
	mmGetCounter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetCounter
}

func (mmGetCounter *mIUsecaseMockGetCounter) invocationsDone() bool {
	if len(mmGetCounter.expectations) == 0 && mmGetCounter.defaultExpectation == nil && mmGetCounter.mock.funcGetCounter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetCounter.mock.afterGetCounterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetCounter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetCounter implements mm_domain.IUsecase
func (mmGetCounter *IUsecaseMock) GetCounter() (c1 mm_domain.Counter, err error) {
	mm_atomic.AddUint64(&mmGetCounter.beforeGetCounterCounter, 1)
	defer mm_atomic.AddUint64(&mmGetCounter.afterGetCounterCounter, 1)

	mmGetCounter.t.Helper()

	if mmGetCounter.inspectFuncGetCounter != nil {
		mmGetCounter.inspectFuncGetCounter()
	}

	if mmGetCounter.GetCounterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetCounter.GetCounterMock.defaultExpectation.Counter, 1)

		mm_results := mmGetCounter.GetCounterMock.defaultExpectation.results
		if mm_results == nil {
			mmGetCounter.t.Fatal("No results are set for the IUsecaseMock.GetCounter")
		}
		return (*mm_results).c1, (*mm_results).err
	}
	if mmGetCounter.funcGetCounter != nil {
		return mmGetCounter.funcGetCounter()
	}
	mmGetCounter.t.Fatalf("Unexpected call to IUsecaseMock.GetCounter.")
	return
}

// GetCounterAfterCounter returns a count of finished IUsecaseMock.GetCounter invocations
func (mmGetCounter *IUsecaseMock) GetCounterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCounter.afterGetCounterCounter)
}

// GetCounterBeforeCounter returns a count of IUsecaseMock.GetCounter invocations
func (mmGetCounter *IUsecaseMock) GetCounterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCounter.beforeGetCounterCounter)
}

// MinimockGetCounterDone returns true if the count of the GetCounter invocations corresponds
// the number of defined expectations
func (m *IUsecaseMock) MinimockGetCounterDone() bool {
	if m.GetCounterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetCounterMock.invocationsDone()
}

// MinimockGetCounterInspect logs each unmet expectation
func (m *IUsecaseMock) MinimockGetCounterInspect() {
	for _, e := range m.GetCounterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to IUsecaseMock.GetCounter")
		}
	}

	afterGetCounterCounter := mm_atomic.LoadUint64(&m.afterGetCounterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetCounterMock.defaultExpectation != nil && afterGetCounterCounter < 1 {
		m.t.Errorf("Expected call to IUsecaseMock.GetCounter at\n%s", m.GetCounterMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCounter != nil && afterGetCounterCounter < 1 {
		m.t.Errorf("Expected call to IUsecaseMock.GetCounter at\n%s", m.funcGetCounterOrigin)
	}

	if !m.GetCounterMock.invocationsDone() && afterGetCounterCounter > 0 {
		m.t.Errorf("Expected %d calls to IUsecaseMock.GetCounter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetCounterMock.expectedInvocations), m.GetCounterMock.expectedInvocationsOrigin, afterGetCounterCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IUsecaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetCounterInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IUsecaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IUsecaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetCounterDone()
}
