# start name:common
version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build project
    cmds:
      - go build -o bin/server ./cmd/server

  run:
    desc: Run project
    cmds:
      - go run ./cmd/server

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...
# end
# start name:gen_rest_models
  oapi_tools:
    desc: Install tool bins
    run: once
    env:
      GOBIN:
        sh: "echo `pwd`/bin"
    cmds:
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0
    sources: # run if changed
      - Taskfile.yml
    generates: # run if missing
      - "bin/oapi-codegen"

  generate_models:
    desc: Generate models
    deps:
      - oapi_tools
    cmds:
      - bin/oapi-codegen --config=api/oapi-codegen.yml api/swagger.yml
#end
