// Package rest_models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rest_models

// Counter defines model for Counter.
type Counter struct {
	Value int `json:"value"`
}
