openapi: 3.0.3
info:
  title: Rest Server User API
  version: 1.0.0
paths:
  /api/counter:
    get:
      summary: Get counter
      operationId: getCounter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
components:
  schemas:
    Counter:
      type: object
      required: [value]
      properties:
        value:
          type: integer
